In [2]:
import torch
import numpy as np

In [3]:
def describe(x):
  print("타입: {}".format(x.type()))
  print("크기: {}".format(x.shape))
  print("값: \n{}".format(x))

In [4]:
describe(torch.Tensor(2, 3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[3.2192e-34, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [5]:
describe(torch.rand(2, 3))
describe(torch.randn(2, 3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.9443, 0.4993, 0.3456],
        [0.9186, 0.8463, 0.5839]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1.3694, 0.9904, 1.4707],
        [1.0037, 1.4620, 0.5206]])


In [6]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5) # _ (파이토치 인-플레이스 메서드)는 텐서 값을 바꾸는 연산을 한다.
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [7]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.8763, 0.4762, 0.6181],
        [0.3739, 0.2726, 0.3740]], dtype=torch.float64)


In [9]:
x = torch.FloatTensor([[1, 2, 3],[4, 5, 6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int64)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
x = x.float()
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
x = torch.randn(2, 3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.3437, -0.5905, -0.8989],
        [-0.5308,  0.4314, -0.1171]])


In [14]:
describe(torch.add(x, x))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.6874, -1.1811, -1.7979],
        [-1.0615,  0.8629, -0.2341]])


In [15]:
describe(x+x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.6874, -1.1811, -1.7979],
        [-1.0615,  0.8629, -0.2341]])


In [16]:
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [17]:
x = x.view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [18]:
describe(torch.sum(x, dim=0))

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [19]:
describe(torch.sum(x, dim=1))

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [20]:
describe(torch.transpose(x, 0, 1))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [21]:
x = x.view(3, 2)
describe(x)

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [22]:
describe(torch.sum(x, dim=0))

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([6, 9])


In [23]:
describe(torch.sum(x, dim=1))

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([1, 5, 9])


In [24]:
x = torch.arange(6).view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
describe(x[:1, :2])

타입: torch.LongTensor
크기: torch.Size([1, 2])
값: 
tensor([[0, 1]])


In [26]:
describe(x[0, 1])

타입: torch.LongTensor
크기: torch.Size([])
값: 
1


In [27]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [28]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [29]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


In [30]:
x = torch.arange(6).view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [31]:
describe(torch.cat([x, x], dim=0))

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [32]:
describe(torch.cat([x, x], dim=1))

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [33]:
describe(torch.stack([x, x]))

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [34]:
x1 = torch.arange(6).view(2, 3)
describe(x1)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [35]:
x2 = torch.ones(3, 2).long()
x2[:, 1] += 1
describe(x2)

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[1, 2],
        [1, 2],
        [1, 2]])


In [36]:
describe(torch.mm(x1, x2))

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3,  6],
        [12, 24]])


In [37]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [38]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [39]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([])
값: 
21.0
False


In [40]:
print(torch.cuda.is_available)

<function is_available at 0x7f2dfc1eab80>


In [42]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [43]:
x = torch.rand(3, 3).to(device)
describe(x)

타입: torch.cuda.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.6491, 0.1348, 0.8707],
        [0.8999, 0.0599, 0.9738],
        [0.3451, 0.4622, 0.1323]], device='cuda:0')


In [45]:
y = torch.rand(3, 3)
cpu_device = torch.device("cpu")
y = y.to(cpu_device)
x = x.to(cpu_device)
x+y

tensor([[1.4953, 0.6762, 1.6850],
        [1.5432, 0.7144, 1.6293],
        [1.0513, 1.3890, 0.1382]])

In [46]:
#CUDA_VISIBLE_DEVICE=0,1,2,3 python main.py